[package]
name = "my_project"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
serde_json = "1.0"
structopt = "0.3.21"
tokio = { version = "1", features = ["full"] }
bitcoin = "0.26.0"

